org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.1.2
enabled_platforms=fabric,neoforge

mod_id=breakingbedrock
mod_version=1.2.0
maven_group=net.anawesomguy.breakingbedrock
description=Allow bedrock to be mined with a netherite pickaxe!
github=AnAwesomGuy/breakingbedrock
display_name=Breaking Bedrock

fabric_loader_version=0.19.3
fabric_api_version=0.153.0+26.1.2

neoforge_version=26.1.2.76

changelog=experimental fork: deobfuscated build, updated to 26.1.2
curseforge_id=1017910
modrinth_id=s0tNTkDN

#testing mods
modernfix_version=5.20.0+mc1.21.1
ferrite_core_version=7.0.2
#sodium_version=mc1.21.1-0.6.5