modLoader="javafml"
loaderVersion="[1,)"
license="Apache-2.0"
issueTrackerURL="${github_repo}/issues"
logoFile="assets/${mod_id}/icon.png"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${display_name}"
authors="AnAwesomGuy"
description="${description}"
displayURL="http://modrinth.com/mod/${modrinth_id}"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"